<div class="row">
	<div class="col-xs-12 text-center">
		<p><big><b>Welcome to the Apretaste Sandbox.</b></big></p>
		<br/>
	</div>
</div>

<div class="row">
	<div class="col-xs-4">
		<div class="panel panel-success">
			<div class="panel-heading">Productivity</div>
			<div class="panel-body">
				<a href="run">Test a service</a><br/>
			</div>
		</div>
		
		<div class="panel panel-success">
			<div class="panel-heading">References</div>
			<div class="panel-body">
				<a href="https://github.com/Apretaste/Core" target="_blank">GitHub repo</a><br/>
				<a href="https://docs.google.com/spreadsheets/d/1M1FPo_JYjrKgEpOdVIlOmTLwSzV9g-ZITuwUYlGjO8o" target="_blank">List of services</a><br/>
				<a href="https://drive.google.com/folderview?id=0B8BgVCFpPBzRMmpPQllMSVZha1U" target="_blank">Services done</a><br/>
			</div>
		</div>
	</div>

	<div class="col-xs-4">
		<div class="panel panel-success">
			<div class="panel-heading">Guidance</div>
			<div class="panel-body">
				<a href="https://docs.google.com/document/d/1KSkIYcuO5LUQr3M62NHqS0EW7UYRRYT1jrnh8fSkRTI" target="_blank">Apretaste manual (Spanish)</a><br/>
				<a href="http://www.smarty.net/crash_course" target="_blank">Smarty crash course</a><br/>
				<a href="http://www.smarty.net/docs/en/" target="_blank">Smarty manual</a><br/>
				<a href="http://symfony.com/doc/current/components/dom_crawler.html" target="_blank">DOM Crawler manual</a><br/>
			</div>
		</div>
	</div>

	<div class="col-xs-4">
		<div class="alert alert-warning" role="alert">
			<p>Welcome to Apretaste Sandbox. Make yourself at home. I hope you have a lot of fun coding :-D</p>
			<p>Check the Apretaste manual, and email me at <b>salvi.pascual@gmail.com</b> with any questions.</p>
			<p><b>Happy Hacking!</b></p>
		</div>
	</div>
</div>
