<?php 
	$wwwhttp = $this->di->get('path')['http'];
?>

<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Apretaste Sandbox</title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="icon" href="<?php echo $wwwhttp; ?>/images/apretaste.icon.png">
		<link href="<?php echo $wwwhttp; ?>/css/bootstrap.min.css" rel="stylesheet">
		<script src="<?php echo $wwwhttp; ?>/js/jquery.js"></script>
		<script src="<?php echo $wwwhttp; ?>/js/bootstrap.min.js"></script>
	</head>

	<body>
		<nav class="navbar navbar-inverse" style="border-radius:0px; -webkit-border-radius:0px; -moz-border-radius:0px;">
			<div class="container">
				<div class="navbar-header">
					<span class="navbar-brand"style="text-transform: uppercase;"><?php if(isset($title)) echo $title; ?></span>
				</div>
				<div class="navbar-right">
					<a href="/" class="btn btn-default navbar-btn">Home</a>
				</div>
			</div>
		</nav>

		<div class="container">
			<?php echo $this->getContent(); ?>
		</div>
	</body>
</html>